# Generated by Django 3.1.4 on 2022-02-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinfo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='picture/'),
        ),
    ]
