# Generated by Django 3.1.4 on 2022-01-20 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ParkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(default='公園', max_length=50)),
                ('playset_swing', models.CharField(max_length=10)),
                ('playset_slide', models.CharField(max_length=10)),
                ('playset_sandbox', models.CharField(max_length=10)),
                ('vending_machine', models.CharField(max_length=10)),
                ('water_services', models.CharField(max_length=10)),
                ('bicycle_parking', models.CharField(max_length=10)),
                ('parking', models.CharField(max_length=10)),
                ('add_info', models.TextField()),
                ('image', models.FileField(null=True, upload_to='picture/')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map_app.positions')),
            ],
        ),
    ]
