# Generated by Django 3.1.4 on 2022-01-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=50)),
                ('playset_swing', models.CharField(max_length=10)),
                ('playset_slide', models.CharField(max_length=10)),
                ('playset_sandbox', models.CharField(max_length=10)),
                ('vending_machine', models.CharField(max_length=10)),
                ('water_services', models.CharField(max_length=10)),
                ('bicycle_parking', models.CharField(max_length=10)),
                ('parking', models.CharField(max_length=10)),
                ('add_info', models.TextField(blank=True)),
                ('image', models.FileField(null=True, upload_to='picture/')),
                ('lat', models.DecimalField(decimal_places=17, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=17, max_digits=20)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
